### ISSUE TITLE
Can't find the repo on the npm registry

### ISSUE THREAD

**Issue by pancho111203** [marmelab/aor-simple-graphql-client#10]
Hi, first of all, thanks for building this!

I am trying to install it via npm but the repo is not found:

'error Couldn't find package "aor-simple-graphql-client" on the "npm" registry.'

**Comment by djhi** [comment]
Hi,

Yes, it has not been published yet. I was hoping to find time to build an example app. I guess we'll publish first and add that example in the readme later then.

**Comment by djhi** [comment]
Version 0.0.1 has been published. Enjoy!
