### ISSUE TITLE
Could not get sample to work, provide working example

### ISSUE THREAD

**Issue by thachp** [marmelab/aor-simple-graphql-client#13]
Could not get this graphql client to work on admin-on-rest.  Can you please provide a working example? The example under Usage in Readme contains a few errors.

Ie, ApolloClient is never imported.  createRestClient is not used anywhere.

Also, Request URL seem to always default to http://localhost:3000/graphql, even though I defined my URL in clientOptions to http://localhost.dev/graphql.

![image](https://cloud.githubusercontent.com/assets/1495371/23592417/5db0e8c8-01b5-11e7-900b-94df38d43a2d.png)

**Comment by djhi** [comment]
Hi, yes we are working on a sample app using this client. I'll fix the README asap. Thanks for reporting this

**Comment by djhi** [comment]
@thachp I fixed the client. Please note that the `url` parameter has been renamed to `uri` to be consistent with Apollo naming. A sample app will be provided soon

**Comment by thachp** [comment]
awesome thank you!
