### ISSUE TITLE
Supply your own queries and mutations confusion

### ISSUE THREAD

**Issue by rigobcastro** [marmelab/aor-simple-graphql-client#20]
Hi, I followed the documentation about this theme but I don't know where place my queries constant. I tried placing the queries constant on buildApolloClient options but doesn't work:

```javascript

const queries = {
  Post: {
    // Is an example, but doesn't works.
    CREATE: () => gql`
        mutation createPost($data: String, $myCustomVar: String){
            createPost(data: $data, myCustomVar: $myCustomVar) {
                id
            }
        }
    `
  }
}

buildApolloClient({ queries })
```

I got the following error:

![captura de pantalla 2017-03-22 a las 3 28 11 p m](https://cloud.githubusercontent.com/assets/1006483/24219293/3af4a286-0f14-11e7-8b76-b9bdc1338581.png)

I'm doing something wrong but I do not know what, thanks for the support.

**Comment by djhi** [comment]
You can't and it won't be possible before long if it will.

**Comment by rigobcastro** [comment]
Thanks for your answer, that is how it was the documentation therefore I got confused.
