### ISSUE TITLE
Support for subfields

### ISSUE THREAD

**Issue by rigobcastro** [marmelab/aor-simple-graphql-client#21]
Hi I have problems when I trying to use a Schema with sub-fields, the error is the next:

```
message: 'Field "user" of type "[Post]" must have a selection of subfields. Did you mean "user { ... }"?
```

Looks easy to fix, but on this package is very complicated. Please look my schema and more stuff for understand more.

Part of my Schema:

``` graphql
type Post {
   id: ID
   name: String
   user: User
}

type User {
  id: ID
  name: String
  email: String
}

type getPageOfPosts{
  items: [Post]
  totalCount: Int
}

query  {
  getPageOfPosts(page: Int, perPage: Int, sortField: String, sortOrder: String, filter: String): getPageOfPosts
}

schema {
  query: Query
}
```

The query sent automatically:

``` graphql
query getPageOfPosts($page: Int, $perPage: Int, $sortField: String, $sortOrder: String, $filter: String) {
  getPageOfPosts(page: $page, perPage: $perPage, sortField: $sortField, sortOrder: $sortOrder, filter: $filter) {
    items {
       id
       name
       user
    }
    totalCount
    __typename
  }
}
```

Query expected (Items part):

```graphql

...

items {
   id
   name
   user {
     id
     name
     email
   }
}

...

```

Thanks for your support!

**Comment by djhi** [comment]
Hi, we don't provide support through github issues. Please use stackoverflow for that. However, the error message is explicit: your query is wrong because user is an object and you have to specify which of its fields you want.

```js
query getPageOfPosts($page: Int, $perPage: Int, $sortField: String, $sortOrder: String, $filter: String) {
  getPageOfPosts(page: $page, perPage: $perPage, sortField: $sortField, sortOrder: $sortOrder, filter: $filter) {
    items {
       id
       name
       user {
           id
           name
           email
       }
    }
    totalCount
    __typename
  }
}
```

**Comment by rigobcastro** [comment]
Hi, thanks for your answer, I didn't know that I should request support here. 

If you notice my request, I wrote the solution you give me, but I do not know where to place it. I need only the correct way. Thanks and sorry for posting.
