### ISSUE TITLE
"Cannot read property 'GET_LIST' of undefined" or incomplete README

### ISSUE THREAD

**Issue by Thebigbignooby** [marmelab/aor-simple-graphql-client#22]
having followed the README guide, I am a little frustrated.

I can see the graphql introspection query in my network tab and It does get all the type and inputs from my schema, but nothing for the queries and mutations.

```javascript
{
  "queryType": {
    "name":"Query"
  },
  "mutationType": {
    "name":"Mutation"
  },
  //...
}
```

I have this
```javascript
componentDidMount() {
      buildApolloClient({ clientOptions, introspection: introspectionOptions })
          .then(restClient => this.setState({ restClient }));
  }
```

where clientOptions is 
```javascript
const apiUrl = process.env.REACT_APP_API_URL
export const clientOptions = {
  uri: `${apiUrl}/graphql`
}
```

and introspectionOptions is the same as in README : 

```javascript
import pluralize from 'pluralize'

export const introspectionOptions = {
  includeTypes: null, // Either an array of types to include or a function which will be called with each OBJECT type discovered through introspection
  excludeTypes: null, // Either an array of types to exclude or a function which will be called with each OBJECT type discovered through introspection (`Query` and `Mutation` are excluded anyway)
  includeQueries: null, // Either an array of queries to include or a function which will be called with each query discovered through introspection
  excludeQueries: null, // Either an array of queries to exclude or a function which will be called with each query discovered through introspection
  includeMutations: null, // Either an array of mutations to include or a function which will be called with each mutation discovered through introspection
  excludeMutations: null, // Either an array of mutations to exclude or a function which will be called with each mutation discovered through introspection
  excludeFields: null, // Either an array of fields to exclude or a function which will be called with each field discovered through introspection on a specific object (more details below)

  // This contains templates for defining the queries and mutations names which will also be used as the operations names
  templates: {
    GET_LIST: resourceType => `getPageOf${pluralize(resourceType.name)}`,
    GET_ONE: resourceType => `get${resourceType.name}`,
    CREATE: resourceType => `create${resourceType.name}`,
    UPDATE: resourceType => `update${resourceType.name}`,
    DELETE: resourceType => `remove${resourceType.name}`,
  },
}
```

Am I missing something ?

**Comment by djhi** [comment]
- Have you tried without passing introspection options at all (if they are the same as the defaults one) ?
- In your network tab, can you check that your server does returns your queries and mutations as the response of the introspection query ?
- What are you using for your graphql server ?

**Comment by Thebigbignooby** [comment]
- Yes I had previously tried without the introspectionOptions which resulted in the same error.
- As mentionned above, I am not receiving my queries nor mutations from my graphql server

![gql-introspection-data](https://cloud.githubusercontent.com/assets/4172090/24453121/d9e5bcaa-1486-11e7-815e-954c693fc364.PNG)

I am using graphql on node.js with `graphql-server-express`

**Comment by djhi** [comment]
Well, this is very strange indeed. What versions of `graphql-server-express` are you using ?

**Comment by Thebigbignooby** [comment]
`"graphql-server-express": "^0.6.0",`

**Comment by djhi** [comment]
I don't know then, we are using the "standard" `introspectionQuery` from the `graphql` package so, if neither the queries not the mutations are presents in the response, you should double check your schema. It has to be a problem on the server side.

**Comment by djhi** [comment]
Can you share your schema ? Part of it at least (declarations of the queries and mutations without their content) ?

**Comment by Thebigbignooby** [comment]
Server is fine, graphiql works, and the api is running in production

**Comment by Thebigbignooby** [comment]
the problem is definitely not on the server.

Is there something else to be done to configure the appollo client ?

i see there is an option to configure our own queries, from the Readme : 

```javascript
const queries = {
    Post: {
        GET_LIST: () => gql`your query`, // Variables will be: { page: Int, perPage: Int, sortFilter: String, sortOrder: String, filter: String }
        GET_MANY: () => gql`your query`, // Optional, see note below. Variables will be: { filter: String }
        GET_MANY_REFERENCE: () => gql`your query`, // Optional, see note below. Variables will be: { filter: String }
        GET_ONE: () => gql`your query`, // Variables will be: { id: ID }
        CREATE: () => gql`your query`, // Variables will be: { data: String }
        UPDATE: () => gql`your query`, // Variables will be: { data: String }
        DELETE: () => gql`your query`, // Variables will be: { id: ID }
    }
}
```

however its unclear how to include this in the appollo client.

I will share our schema decleration if you still think it will help

**Comment by djhi** [comment]
No you shouldn't have anything to configure on the apollo client.

About the `queries` option, simply pass it to the `buildApolloClient` as you do with `clientOptions` and `introspection`.

**Comment by Thebigbignooby** [comment]
this is how we build our schema

```javascript
const rootSchema = `
type Query {
  ${favoriteQueries}
  ${userQueries}
  ${propertyQueries}
  ${purchaseQueries}
  ${servicePackQueries}
  ${conversationQueries}
}

type Mutation {
  ${favoriteMutations}
  ${userMutations}
  ${propertyMutations}
  ${purchaseMutations}
  ${servicePackMutations}
  ${conversationMutations}
}

schema {
  query: Query
  mutation: Mutation
}
`

// Put schema together into one array of schema strings
// and one map of resolvers, like makeExecutableSchema expects
const schema = [rootSchema, favoriteTypes, userTypes, propertyTypes, purchaseTypes, servicePackTypes, conversationTypes]
const resolvers = merge(favoriteResolvers, userResolvers, propertyResolvers, purchaseResolvers, servicePackResolvers,
  conversationResolvers)

const executableSchema = makeExecutableSchema({
  typeDefs: schema,
  resolvers
})

export default executableSchema
```

When I try the introspection by hand in graphiql, I get the same result : 
![graphiql-introspection-test](https://cloud.githubusercontent.com/assets/4172090/24455864/6ae11d1c-1491-11e7-9921-f5e96c4eb0b6.PNG)

I can get my types but not the queries.
However, the introspection query the GraphiQL does manages to get this information, as it is present in GraphiQL schema Docs . . .

**Comment by djhi** [comment]
The introspection query is actually a little more complicated, that's why we use the official one: https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js

**Comment by Thebigbignooby** [comment]
Even with the query that you linked to, I don't receive my queries and mutation, but with the following query I do:

```javascript
__schema {
    queryType {
      name
      fields {
        name
        description
        type { 
          name
          kind
        }
        args { 
          name
          type { 
            name
            kind 
            ofType { 
              name
              kind
            }
          }
        }
      }
    }
  }
```

... Is this approach deprecated ?

**Comment by djhi** [comment]
You mean you tried this query in graphiql and didn't receive the expected data ?

**Comment by Thebigbignooby** [comment]
Result using the official introspection query you linked to : 
![stantard-introspection-not-working](https://cloud.githubusercontent.com/assets/4172090/24458672/e5290b40-1499-11e7-8d06-bb6005f81daa.PNG)


Result using the query I pasted above
![working-instrospection](https://cloud.githubusercontent.com/assets/4172090/24458506/6a5e9c4a-1499-11e7-980c-a0837e92fc97.PNG)

**Comment by djhi** [comment]
The strange thing is that `aor-simple-graphql-client` use the official introspection query as you can see [here](https://github.com/marmelab/aor-simple-graphql-client/blob/master/src/introspection/fetchSchema.js)

**Comment by djhi** [comment]
oh wait, misread...

**Comment by djhi** [comment]
This is really really weird. I use this package as is, without special configuration on a projet of mine and it works.

**Comment by djhi** [comment]
I'm using the `graphql-server-koa` package on server side though.

**Comment by djhi** [comment]
And you can see [here](https://github.com/graphql/graphiql/blob/master/src/utility/introspectionQueries.js) that this is the query used by graphiql too

**Comment by Thebigbignooby** [comment]
Inspecting the network tab when using graphiql, the initial introspection query does not return anything for the queries and mutations, however I still get the correct queries and mutations in the generated docs, which is weird.

I now have a doubt and am going to play around with my server.

**Comment by djhi** [comment]
Please do explain what happened when you find it

**Comment by Thebigbignooby** [comment]
looking more closely at the introspection comparison screenshots, it looks like the "official" introspection query is getting my queries and mutations, but as part of `types` instead of `queryType`, and somehow graphiQL can manage this kind of response.

**Comment by Thebigbignooby** [comment]
It's not the server, whatever I try ends up in a Graphql Error, Its got to be the introspection query.

Perhaps graphiQL has other ways of getting information about the queries and mutations if they are not present in  `queryType` & `mutationType` of the introspection response?

**Comment by djhi** [comment]
The only difference I see between your project and mine is that I use `extend Query` to separate my queries in different files when you "concatenate" your queries. But this should not impact the way the schema is built

**Comment by Thebigbignooby** [comment]
For now, I will make do with our in-house graphql-rest-client for AOR.
I want to explore this further however when I have the time

**Comment by djhi** [comment]
Np: FIY my project using aor and this client is https://github.com/djhi/dpc

**Comment by Thebigbignooby** [comment]
Hi, 
So I have begun a side project, using [Graph Cool](https://www.graph.cool/) as my graphQL backend
And i'm having the exact same issue.

Below you see that nothing is returned in the `query` part of the response
![greenplate-1](https://cloud.githubusercontent.com/assets/4172090/25344368/3019bd5c-2912-11e7-868f-b8a0b981b01d.PNG)

However, below, you can see in the Appollo dev tools that GraphiQL has no problem getting this information.

![greenplate-2](https://cloud.githubusercontent.com/assets/4172090/25344380/340bc19e-2912-11e7-9ff4-11e67baed59c.PNG)

I invite you to try out a sample schema on Graph Cool to see for youself.

The only conclusion I draw from this is that something is missing from the introspection query used in this package . . .

**Comment by mulyoved** [comment]
@Thebigbignooby 

check my changes in https://github.com/marmelab/aor-simple-graphql-client/pull/25

let me know if need help

**Comment by Thebigbignooby** [comment]
@mulyoved 
thanks . . . But i'm confused, what's the hack I'm looking at ?

**Comment by mulyoved** [comment]
This is a fork that adjusts the introspection to fit graph.cool

**Comment by Thebigbignooby** [comment]
I understand, But I don't see what the adjustment is.

**Comment by mulyoved** [comment]
check https://github.com/marmelab/aor-simple-graphql-client/pull/25/files
will see changes made to make it work with graph.cool

**Comment by djhi** [comment]
This client is not compatible with graphcool which requires a very different introspection analysis and does not handle pagination as we do here. Please use @mulyoved version for graphcool

**Comment by vysakh0** [comment]
@mulyoved I'm using `aor-graph-cool-client` library, and I get the same error as this issue. Couldn't create an issue in that repo, please help

```js
import React, { Component } from 'react';
import { simpleRestClient, Admin, Resource } from 'admin-on-rest';
import { buildApolloClient } from 'aor-graph-cool-client';
import { PostList, PostEdit, PostCreate, PostIcon } from './posts';
import { ApolloClient, createNetworkInterface } from 'apollo-client';

class AdminPage extends Component {
    constructor() {
        super();
        this.state = { restClient: null };
    }
    componentDidMount() {
      const client = new ApolloClient({
            networkInterface: createNetworkInterface({
              uri: 'https://api.graph.cool/simple/v1/xxxx' 
        })
      });
        buildApolloClient({client})
            .then(restClient => this.setState({ restClient }));
    }

    render() {
        const { restClient } = this.state;

        if (!restClient) {
            return <div>Loading</div>;
        }

        return (
            <Admin restClient={restClient}>
                <Resource name="Post" list={PostList} edit={PostEdit} create={PostCreate}  />
            </Admin>
        );
    }
}
export default AdminPage
```

**Comment by vysakh0** [comment]
@mulyoved I'm using `aor-graph-cool-client` and still get the error as this issue. Couldn't create an issue in that repo, please help. 

```js
import React, { Component } from 'react';
import { simpleRestClient, Admin, Resource } from 'admin-on-rest';
import { buildApolloClient } from 'aor-graph-cool-client';
import { PostList, PostEdit, PostCreate, PostIcon } from './posts';
import { ApolloClient, createNetworkInterface } from 'apollo-client';

class AdminPage extends Component {
    constructor() {
        super();
        this.state = { restClient: null };
    }
    componentDidMount() {
      const client = new ApolloClient({
            networkInterface: createNetworkInterface({
              uri: 'https://api.graph.cool/simple/v1/cxx' 
        })
      });
        buildApolloClient({client})
            .then(restClient => this.setState({ restClient }));
    }

    render() {
        const { restClient } = this.state;

        if (!restClient) {
            return <div>Loading</div>;
        }

        return (
            <Admin restClient={restClient}>
                <Resource name="Post" list={PostList} edit={PostEdit} create={PostCreate}  />
            </Admin>
        );
    }
}
export default AdminPage
```

**Comment by mulyoved** [comment]
@vysakh0 aor-graph-cool-client is deprecated by the addition of GraphQL flavor, see https://github.com/marmelab/aor-simple-graphql-client

**Comment by djhi** [comment]
I'm afraid however that the new flavor mechanism is not enough yet. I'm trying to make a client for graphcool. Please be patient, I might have something later this week

**Comment by vysakh0** [comment]
@djhi Cool, thank you! :+1:

**Comment by manolkalinov** [comment]
@djhi Is there absolutely NO way to currently hook up **aor-simple-graphql-client** to **graph.cool**? Even with the `queries` and/or `flavor ` objects? I would appreciate if someone has come up with a temporary workaround until the graphcool client comes out.

I've been desperately trying to get this to work for two days now, but docs on this project, as well as @mulyoved's **aor-graph-cool-client** docs lead you in circles and ultimately to a dead end... :). Maybe the READMEs should be updated.

**Comment by djhi** [comment]
Hi there, see #40 :) In a nutshell, I'm working on a new cleaner client.
