### ISSUE TITLE
No introspection data for resources issue

### ISSUE THREAD

**Issue by robdrop** [marmelab/aor-simple-graphql-client#42]
Hi.

I've encountered a problem while working with the client. The thing is I can see queries are fetched in introspection, but they are not occurring while trying to fetch resource list. 

Basing on readme, here's some code of mine
 
```
// users/index.js
import React from 'react';
import { List, Datagrid, TextField } from 'admin-on-rest/lib/mui';

export const UserList = props => (
    <List {...props} sort={{ field: 'created_at', order: 'DESC' }} perPage={25}>
        <Datagrid bodyOptions={{ stripedRows: true, showRowHover: true }}>
            <TextField source="id" />
            <TextField source="name"/>
        </Datagrid>
    </List>
);

```

```
// App.js
import React, { Component } from 'react';
import { buildApolloClient } from 'aor-simple-graphql-client';
import { Admin, Resource } from 'admin-on-rest';
import { UserList } from './users/index';

import './App.css';

class App extends Component {
    constructor() {
        super();
        this.state = { restClient: null };
    }
    componentDidMount() {
        buildApolloClient({ clientOptions: { uri: 'http://localhost:4000/graphql'} })
            .then(restClient => this.setState({ restClient }));
    }

    render() {
        const { restClient } = this.state;

        if (!restClient) {
            return <div>Loading</div>;
        }

        return (
            <Admin
                restClient={restClient}
            >
                <Resource name="Users" list={UserList} />
            </Admin>
        );
    }
}

export default App;

```

![screen shot 2017-07-05 at 20 28 00](https://user-images.githubusercontent.com/29928136/27879023-939eacc0-61c0-11e7-9e08-f988f790031d.png)
**Fetched queries by introspection**

![screen shot 2017-07-05 at 20 24 06](https://user-images.githubusercontent.com/29928136/27879093-cda9fa3c-61c0-11e7-86ee-375923406b2a.png)
**Errors**

![screen shot 2017-07-05 at 20 30 01](https://user-images.githubusercontent.com/29928136/27879112-e6402d1e-61c0-11e7-8b9d-03d12eda94ae.png)
**Server introspection response** 

I appriciate any advice from you.

**Comment by posix4e** [comment]
Yep same problem here

**Comment by djhi** [comment]
This project has been deprecated in favor or [aor-graphql](https://github.com/marmelab/aor-graphql)
