### ISSUE TITLE
Graphcool compatibility

### ISSUE THREAD

**Issue by sorenbs** [marmelab/aor-simple-graphql-client#47]
The readme states that this project is not compatible with Graphcool and we should use https://github.com/mulyoved/aor-graph-cool-client instead. However, that repo is marked as deprecated and suggests to use this repo instead.

Which one is correct? :-)

**Comment by djhi** [comment]
Yeah, sorry about the confusion.

`aor-simple-graphql-client` was our first try at using graphql with aor. We now have a lerna repository with a gql client basis and a graphcool implementation here: https://github.com/marmelab/aor-graphql

**Comment by djhi** [comment]
How did you find this one btw ?

**Comment by sorenbs** [comment]
Ah, thanks! I was googling for `aor graphql` :-)
